services:
    Google\Client:
        class: Google\Client
        calls:
            # Authentication with "API key"
            - [setDeveloperKey, ['%env(YOUTUBE_API_KEY)%']]
            # Authentication with "OAuth 2.0" using Client ID & Secret
            - [setClientId, ['%env(YOUTUBE_CLIENT_ID)%']]
            - [setClientSecret, ['%env(YOUTUBE_CLIENT_SECRET)%']]
            # Authentication with "OAuth 2.0" or "Service account" using JSON
            - [setAuthConfig, ['%env(resolve:YOUTUBE_AUTH_CONFIG)%']]
