vich_uploader:
    db_driver: orm

    mappings:
       cv_expert:
           uri_prefix: '%cv_expert%'
           upload_destination: '%kernel.project_dir%/public%cv_expert%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false