version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laboOlona1
      MYSQL_ROOT_PASSWORD: moissons
    ports:
      - "3306:3306"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025" # Interface web
      - "1025:1025" # Serveur SMTP
